### PR TITLE
Allow overriding requirements on type metapackage

### PR DESCRIPTION
**Pull request by NickDickinsonWilde**
It is possible to add dependencies on internal subsections/modules of a module these then get a composer type of metapackage but also get the drupal core dependencies added.
Example: drupal/calendar (https://www.drupal.org/project/calendar) has a dependency on drupal/calendar_datetime

Could be added to readme but restriction probably unnecessary.

### CODE REVIEW

**Comment by mglaman** [comment]
I'm trying to understand. So we should allow `metapackage` types to be processed, always. What is an example of a metapackage causing this? It doesn't seem that `drupal/calendar` is one.

**Comment by prudloff-insite** [comment]
We encountered the following examples:
* `drupal/webform_ui`
* `drupal/realistic_dummy_content_api`
* `drupal/cacheflush_entity`

Without this patch, this kind of dependency would prevent upgrading to Drupal 10.

**Comment by mglaman** [comment]
Are all of those modules submodules of a module? I didn't think the facade marked those as metadata package types. The original summary makes more sense now, if it was about the submodule.

**Comment by NickDickinsonWilde** [comment]
Yeah the example I was talking about was `drupal/calendar_datetime` which is a sub-module of `drupal/calendar`. I don't know the reasoning behind that being marked as a metapackage etc, just that it is

**Comment by mglaman** [comment]
Thanks! Making a release for this :)

**Pull request merged**
